const data = {
  products: [
    {
      id: 1,
      image: "/images/shirt1.jpg",
      name: "Fit Shirt",
      slug: "fit-shirt",
      brand: "Adidas",
      category: "Shirts",
      price: 80,
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: "Smart Looking shirt",
    },
    {
      id: 2,
      image: "/images/shirt2.jpg",
      name: "Slim Shirt",
      slug: "slim-shirt",
      brand: "Raymond",
      category: "Shirts",
      price: 90,
      rating: 4.9,
      numReviews: 10,
      countInStock: 25,
      description: "Smart Looking shirt",
    },
    {
      id: 3,
      image: "/images/shirt4.jpg",
      name: "Blue Shirt",
      slug: "blue-shirt",
      brand: "Adidas",
      category: "Shirts",
      price: 80,
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: "Smart Looking shirt",
    },
    {
      id: 4,
      image: "/images/shirt5.jpg",
      name: "Free Shirt",
      slug: "free-shirt",
      brand: "Adidas",
      category: "Shirts",
      price: 80,
      rating: 3,
      numReviews: 13,
      countInStock: 15,
      description: "Smart Looking shirt",
    },
    {
      id: 5,
      image: "/images/pants1.jpg",
      name: "Golf Pants",
      slug: "golf-pants",
      brand: "Adidas",
      category: "Pants",
      price: 100,
      rating: 3.9,
      numReviews: 13,
      countInStock: 20,
      description: "Smart Looking Pants",
    },
    {
      id: 6,
      image: "/images/pants2.jpg",
      name: "Fit Pants",
      slug: "fit-pants",
      brand: "Adidas",
      category: "Pants",
      price: 80,
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: "Smart Looking Pants",
    },
  ],
};

export default data;
